test
Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 33, in get
    return render(request, self.template_name, {})
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 198, in compile_nodelist
    return parser.parse()
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 483, in parse
    raise self.error(token, e)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/template/base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 44: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 25, in get
    print(Vehicle.objects.first().max_weight)
AttributeError: 'NoneType' object has no attribute 'max_weight'
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 25, in get
    print(Vehicle.objects.first().max_weight)
AttributeError: 'NoneType' object has no attribute 'max_weight'
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 26, in get
    print(vehicle.max_weight)
AttributeError: 'NoneType' object has no attribute 'max_weight'
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 26, in get
    print(vehicle['max_weight'])
TypeError: 'NoneType' object is not subscriptable
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 26, in get
    print(vehicle['max_weight'])
TypeError: 'NoneType' object is not subscriptable
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 26, in get
    print(vehicle.max_weight)
AttributeError: 'NoneType' object has no attribute 'max_weight'
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 26, in get
    print(vehicle.max_weight)
AttributeError: 'NoneType' object has no attribute 'max_weight'
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 27, in get
    Vehicle.objects.first().update(max_weight=Vehicle.objects.first().max_weight - 100)
AttributeError: 'Vehicle' object has no attribute 'update'
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 27, in get
    Vehicle.objects.filter(name=vehicle.name).update(max_weight=Vehicle.objects.first().max_weight - 100)
AttributeError: 'int' object has no attribute 'name'
Internal Server Error: /np/
Traceback (most recent call last):
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/miroslav/PycharmProjects/Project_nova_poshta-simulator/nova_poshta/main/views.py", line 27, in get
    Vehicle.objects.filter(name=vehicle.name).update(max_weight=Vehicle.objects.first().max_weight - 100)
AttributeError: 'int' object has no attribute 'name'
